#include <Windows.h>
#include <string>
#include <memory>
#include <vector>
#include <map>
#include <tchar.h>

#include "ACPI.h"
#include "CAudio.h"
#include "CPU.h"
#include "DiskLib.h"
#include "EDID.h"
#include "smbioslib.h"
#include "Superio.h"
#include "Iusb.h"
#include "gpu.h"
#include "NetworkLib.h"
#include "Driverdll.h"
#include "MemoryLib.h"
#include "PCI-E.h"