/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe MainWindow.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_SMBIOS
#define VCZH_WORKFLOW_COMPILER_GENERATED_SMBIOS

#include "SmbiosPartialClasses.h"

#endif
