/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe MainWindow.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_SMBIOSPARTIALCLASSES
#define VCZH_WORKFLOW_COMPILER_GENERATED_SMBIOSPARTIALCLASSES

#include "GacUI.h"
#include <string>
#include <map>
#include <functional>

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

namespace vl_workflow_global
{
	struct __vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
	struct __vwsnf22_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_;
	struct __vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_;
	struct __vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
	struct __vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
	struct __vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
	struct __vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
	struct __vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
	struct __vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
	struct __vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
	struct __vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
	struct __vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_;
	struct __vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_;
	struct __vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
	struct __vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
	class __vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter;
	class __vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter;
	class __vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
	class __vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
	class __vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
	class __vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
	class __vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription;
	class __vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription;
}

namespace Smbios
{
	class DataGridTabPageConstructor;
	class DataGridTabPage;
	class DisplayDataToSmbiosData;
	class MainWindowConstructor;
	class MainWindow;
	class ProductInfoPageConstructor;
	class ProductInfoPage;
	class SmbiosTypaDataItem;
	class TextEditorConstructor;
	class TextEditor;

	class DataGridTabPageConstructor : public ::vl::Object, public ::vl::reflection::Description<DataGridTabPageConstructor>
	{
		friend class ::vl_workflow_global::__vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend struct ::vl_workflow_global::__vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<DataGridTabPageConstructor>;
#endif
	protected:
		::Smbios::DataGridTabPage* self;
		::vl::presentation::controls::GuiComboBoxListControl* comboView;
		::vl::presentation::controls::GuiBindableDataGrid* listView;
		::vl::presentation::controls::GuiListView* textList;
		::vl::presentation::compositions::GuiTableComposition* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_1;
		::vl::presentation::controls::GuiTextList* __vwsn_precompile_2;
		::vl::Ptr<::vl::presentation::controls::list::TextItem> __vwsn_precompile_3;
		::vl::Ptr<::vl::presentation::controls::list::TextItem> __vwsn_precompile_4;
		::vl::Ptr<::vl::presentation::controls::list::TextItem> __vwsn_precompile_5;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_6;
		::vl::presentation::compositions::GuiColumnSplitterComposition* __vwsn_precompile_7;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_8;
		::vl::Ptr<::vl::presentation::controls::list::DataColumn> __vwsn_precompile_9;
		::vl::Ptr<::vl::presentation::controls::list::DataColumn> __vwsn_precompile_10;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_11;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_12;
		::vl::Ptr<::vl::presentation::controls::list::ListViewColumn> __vwsn_precompile_13;
		::vl::Ptr<::vl::presentation::controls::list::ListViewColumn> __vwsn_precompile_14;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_15;
		void __vwsn_Smbios_DataGridTabPage_Initialize(::Smbios::DataGridTabPage* __vwsn_this_);
	public:
		DataGridTabPageConstructor();
	};

	class DataGridTabPage : public ::vl::presentation::controls::GuiTabPage, public ::Smbios::DataGridTabPageConstructor, public ::vl::reflection::Description<DataGridTabPage>
	{
		friend class ::Smbios::DataGridTabPageConstructor;
		friend class ::vl_workflow_global::__vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend struct ::vl_workflow_global::__vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<DataGridTabPage>;
#endif
	protected:
		void ListView_Selection_Changed(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments);
	public:
		DataGridTabPage();
		void __vwsn_instance_ctor_();
		~DataGridTabPage();

		/* USER_CONTENT_BEGIN(custom members of ::Smbios::DataGridTabPage) */
		decltype(auto) GetTestList() const
		{
			return textList;
		}
	private:
		std::map<int, std::function<void(void*, decltype(textList))>> TypeFunctions;
		std::string Vendor;
		void CreateTextlistData();
		/* USER_CONTENT_END() */
	};

	class DisplayDataToSmbiosData : public ::vl::Object, public ::vl::reflection::Description<DisplayDataToSmbiosData>
	{
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<DisplayDataToSmbiosData>;
#endif
	private:
		::vl::WString __vwsn_prop_Desc;
	public:
		::vl::WString GetDesc();
		void SetDesc(const ::vl::WString& __vwsn_value_);
	private:
		::vl::WString __vwsn_prop_Display;
	public:
		::vl::WString GetDisplay();
		void SetDisplay(const ::vl::WString& __vwsn_value_);
	private:
		::vl::vint __vwsn_prop_SmbiosType;
	public:
		::vl::vint GetSmbiosType();
		void SetSmbiosType(::vl::vint __vwsn_value_);
	private:
		::vl::WString __vwsn_prop_SmbiosTypeValue;
	public:
		::vl::WString GetSmbiosTypeValue();
		void SetSmbiosTypeValue(const ::vl::WString& __vwsn_value_);
		DisplayDataToSmbiosData();
		DisplayDataToSmbiosData(const ::vl::WString& desc, const ::vl::WString& display, const ::vl::vint& type, const ::vl::WString& value);
	};

	class MainWindowConstructor : public ::vl::Object, public ::vl::reflection::Description<MainWindowConstructor>
	{
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindowConstructor>;
#endif
	protected:
		::Smbios::MainWindow* self;
		::vl::presentation::controls::GuiTab* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_1;
		::Smbios::DataGridTabPage* __vwsn_precompile_2;
		::Smbios::ProductInfoPage* __vwsn_precompile_3;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_4;
		void __vwsn_Smbios_MainWindow_Initialize(::Smbios::MainWindow* __vwsn_this_);
	public:
		MainWindowConstructor();
	};

	class MainWindow : public ::vl::presentation::controls::GuiWindow, public ::Smbios::MainWindowConstructor, public ::vl::reflection::Description<MainWindow>
	{
		friend class ::Smbios::MainWindowConstructor;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindow>;
#endif
	public:
		MainWindow();
		~MainWindow();
	};

	class ProductInfoPageConstructor : public ::vl::Object, public ::vl::reflection::Description<ProductInfoPageConstructor>
	{
		friend class ::vl_workflow_global::__vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend struct ::vl_workflow_global::__vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<ProductInfoPageConstructor>;
#endif
	protected:
		::Smbios::ProductInfoPage* self;
		::vl::presentation::controls::GuiComboBoxListControl* comboView;
		::vl::presentation::controls::GuiBindableDataGrid* listView;
		::vl::presentation::compositions::GuiTableComposition* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_1;
		::vl::presentation::controls::GuiTextList* __vwsn_precompile_2;
		::vl::Ptr<::vl::presentation::controls::list::TextItem> __vwsn_precompile_3;
		::vl::Ptr<::vl::presentation::controls::list::TextItem> __vwsn_precompile_4;
		::vl::Ptr<::vl::presentation::controls::list::TextItem> __vwsn_precompile_5;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_6;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_7;
		::vl::Ptr<::vl::presentation::controls::list::DataColumn> __vwsn_precompile_8;
		::vl::Ptr<::vl::presentation::controls::list::DataColumn> __vwsn_precompile_9;
		::vl::Ptr<::vl::presentation::controls::list::DataColumn> __vwsn_precompile_10;
		::vl::Ptr<::vl::presentation::controls::list::DataColumn> __vwsn_precompile_11;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_12;
		void __vwsn_Smbios_ProductInfoPage_Initialize(::Smbios::ProductInfoPage* __vwsn_this_);
	public:
		ProductInfoPageConstructor();
	};

	class ProductInfoPage : public ::vl::presentation::controls::GuiTabPage, public ::Smbios::ProductInfoPageConstructor, public ::vl::reflection::Description<ProductInfoPage>
	{
		friend class ::Smbios::ProductInfoPageConstructor;
		friend class ::vl_workflow_global::__vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend class ::vl_workflow_global::__vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter;
		friend struct ::vl_workflow_global::__vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_;
		friend struct ::vl_workflow_global::__vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
		friend struct ::vl_workflow_global::__vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<ProductInfoPage>;
#endif
	public:
		ProductInfoPage();
		void __vwsn_instance_ctor_();
		~ProductInfoPage();
	};

	class SmbiosTypaDataItem : public ::vl::Object, public ::vl::reflection::Description<SmbiosTypaDataItem>
	{
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<SmbiosTypaDataItem>;
#endif
	private:
		::vl::WString __vwsn_prop_Desc;
	public:
		::vl::WString GetDesc();
		void SetDesc(const ::vl::WString& __vwsn_value_);
	private:
		::vl::vint __vwsn_prop_Type;
	public:
		::vl::vint GetType();
		void SetType(::vl::vint __vwsn_value_);
	private:
		::vl::vint64_t __vwsn_prop_Address;
	public:
		::vl::vint64_t GetAddress();
		void SetAddress(::vl::vint64_t __vwsn_value_);
		SmbiosTypaDataItem();
		SmbiosTypaDataItem(const ::vl::vint& type, const ::vl::WString& desc, const ::vl::vint64_t& addr);
	};

	class TextEditorConstructor : public ::vl::Object, public ::vl::reflection::Description<TextEditorConstructor>
	{
		friend class ::vl_workflow_global::__vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf22_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<TextEditorConstructor>;
#endif
	protected:
		::Smbios::TextEditor* self;
		::vl::presentation::controls::GuiLabel* textLabel;
		void __vwsn_Smbios_TextEditor_Initialize(::Smbios::TextEditor* __vwsn_this_);
	public:
		TextEditorConstructor();
	};

	class TextEditor : public ::vl::presentation::templates::GuiGridEditorTemplate, public ::Smbios::TextEditorConstructor, public ::vl::reflection::Description<TextEditor>
	{
		friend class ::Smbios::TextEditorConstructor;
		friend class ::vl_workflow_global::__vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf22_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<TextEditor>;
#endif
	public:
		TextEditor();
		~TextEditor();
	};
}
/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class Smbios
	{
	public:

		static Smbios& Instance();
	};

	/***********************************************************************
	Closures
	***********************************************************************/

	struct __vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::reflection::description::Value operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const;
	};

	struct __vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsn_item_) const;
	};

	struct __vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::reflection::description::Value operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const;
	};

	struct __vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsn_item_) const;
	};

	struct __vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::reflection::description::Value operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const;
	};

	struct __vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsn_item_) const;
	};

	struct __vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::reflection::description::Value operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const;
	};

	struct __vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsn_item_) const;
	};

	struct __vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_
	{
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsnf22_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_
	{
		::Smbios::TextEditorConstructor* __vwsnthis_0;

		__vwsnf22_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_(::Smbios::TextEditorConstructor* __vwsnctorthis_0);

		void operator()(const ::vl::reflection::description::Value& __vwsn_value_) const;
	};

	struct __vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_
	{
		::Smbios::TextEditorConstructor* __vwsnthis_0;

		__vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_(::Smbios::TextEditorConstructor* __vwsnctorthis_0);

		void operator()(const ::vl::reflection::description::Value& __vwsn_value_) const;
	};

	struct __vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_
	{
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		::vl::reflection::description::Value operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const;
	};

	struct __vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_
	{
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsn_item_) const;
	};

	struct __vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_
	{
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		::vl::reflection::description::Value operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const;
	};

	struct __vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_
	{
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		::vl::WString operator()(const ::vl::reflection::description::Value& __vwsn_item_) const;
	};

	struct __vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_
	{
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_
	{
		::vl::presentation::controls::list::IDataSorter* __vwsnthis_0;
		::Smbios::ProductInfoPageConstructor* __vwsnthis_1;

		__vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1);

		::vl::vint operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const;
	};

	struct __vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_
	{
		::vl::presentation::controls::list::IDataSorter* __vwsnthis_0;
		::Smbios::ProductInfoPageConstructor* __vwsnthis_1;

		__vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1);

		::vl::vint operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const;
	};

	struct __vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_
	{
		::vl::presentation::controls::list::IDataSorter* __vwsnthis_0;
		::Smbios::ProductInfoPageConstructor* __vwsnthis_1;

		__vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1);

		::vl::vint operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const;
	};

	struct __vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_
	{
		::vl::presentation::controls::list::IDataSorter* __vwsnthis_0;
		::Smbios::DataGridTabPageConstructor* __vwsnthis_1;

		__vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::DataGridTabPageConstructor* __vwsnctorthis_1);

		::vl::vint operator()(::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_1, ::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_2) const;
	};

	struct __vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_
	{
		::vl::presentation::controls::list::IDataSorter* __vwsnthis_0;
		::Smbios::DataGridTabPageConstructor* __vwsnthis_1;

		__vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::DataGridTabPageConstructor* __vwsnctorthis_1);

		::vl::vint operator()(::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_1, ::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_2) const;
	};

	struct __vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_
	{
		::Smbios::DataGridTabPage* __vwsn_this_;
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPage* __vwsnctor___vwsn_this_, ::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* __vwsno_1, ::vl::presentation::compositions::GuiEventArgs* __vwsno_2) const;
	};

	struct __vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_
	{
		::vl::presentation::controls::list::IDataSorter* __vwsnthis_0;
		::Smbios::ProductInfoPageConstructor* __vwsnthis_1;

		__vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1);

		::vl::vint operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const;
	};

	class __vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter : public ::vl::Object, public virtual ::vl::presentation::controls::list::IDataSorter
	{
	public:
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		void SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value) override;
		::vl::vint Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_) override;
	};

	class __vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter : public ::vl::Object, public virtual ::vl::presentation::controls::list::IDataSorter
	{
	public:
		::Smbios::DataGridTabPageConstructor* __vwsnthis_0;

		__vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0);

		void SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value) override;
		::vl::vint Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_) override;
	};

	class __vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter : public ::vl::Object, public virtual ::vl::presentation::controls::list::IDataSorter
	{
	public:
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		void SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value) override;
		::vl::vint Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_) override;
	};

	class __vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter : public ::vl::Object, public virtual ::vl::presentation::controls::list::IDataSorter
	{
	public:
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		void SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value) override;
		::vl::vint Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_) override;
	};

	class __vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter : public ::vl::Object, public virtual ::vl::presentation::controls::list::IDataSorter
	{
	public:
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		void SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value) override;
		::vl::vint Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_) override;
	};

	class __vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter : public ::vl::Object, public virtual ::vl::presentation::controls::list::IDataSorter
	{
	public:
		::Smbios::ProductInfoPageConstructor* __vwsnthis_0;

		__vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0);

		void SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value) override;
		::vl::vint Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_) override;
	};

	class __vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription : public ::vl::Object, public virtual ::vl::reflection::description::IValueSubscription
	{
	public:
		::Smbios::TextEditorConstructor* __vwsnthis_0;

		__vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription(::Smbios::TextEditorConstructor* __vwsnctorthis_0);

		::Smbios::TextEditor* __vwsn_bind_cache_0 = nullptr;
		::vl::Ptr<::vl::reflection::description::IEventHandler> __vwsn_bind_handler_0_0;
		bool __vwsn_bind_opened_ = false;
		bool __vwsn_bind_closed_ = false;
		void __vwsn_bind_activator_();
		void __vwsn_bind_callback_0_0(::vl::presentation::compositions::GuiGraphicsComposition* __vwsn_bind_callback_argument_0, ::vl::presentation::compositions::GuiEventArgs* __vwsn_bind_callback_argument_1);
		bool Open() override;
		bool Update() override;
		bool Close() override;
	};

	class __vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription : public ::vl::Object, public virtual ::vl::reflection::description::IValueSubscription
	{
	public:
		::Smbios::TextEditorConstructor* __vwsnthis_0;

		__vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription(::Smbios::TextEditorConstructor* __vwsnctorthis_0);

		::vl::presentation::controls::GuiLabel* __vwsn_bind_cache_0 = nullptr;
		::vl::Ptr<::vl::reflection::description::IEventHandler> __vwsn_bind_handler_0_0;
		bool __vwsn_bind_opened_ = false;
		bool __vwsn_bind_closed_ = false;
		void __vwsn_bind_activator_();
		void __vwsn_bind_callback_0_0(::vl::presentation::compositions::GuiGraphicsComposition* __vwsn_bind_callback_argument_0, ::vl::presentation::compositions::GuiEventArgs* __vwsn_bind_callback_argument_1);
		bool Open() override;
		bool Update() override;
		bool Close() override;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif

#endif
// UNUSED_USER_CONTENT:
//		/* USER_CONTENT_BEGIN(custom members of ::Smbios::ProductInfoPage) */
//		/* USER_CONTENT_END() */
