/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe MainWindow.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "SmbiosReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(Smbios::DataGridTabPage)
			IMPL_CPP_TYPE_INFO(Smbios::DataGridTabPageConstructor)
			IMPL_CPP_TYPE_INFO(Smbios::DisplayDataToSmbiosData)
			IMPL_CPP_TYPE_INFO(Smbios::MainWindow)
			IMPL_CPP_TYPE_INFO(Smbios::MainWindowConstructor)
			IMPL_CPP_TYPE_INFO(Smbios::ProductInfoPage)
			IMPL_CPP_TYPE_INFO(Smbios::ProductInfoPageConstructor)
			IMPL_CPP_TYPE_INFO(Smbios::SmbiosTypaDataItem)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_CLASS_MEMBER(::Smbios::DataGridTabPage)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiTabPage)
				CLASS_MEMBER_BASE(::Smbios::DataGridTabPageConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::Smbios::DataGridTabPage*(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_instance_ctor_, NO_PARAMETER)
				CLASS_MEMBER_METHOD(ListView_Selection_Changed, { L"sender" _ L"arguments" })
			END_CLASS_MEMBER(::Smbios::DataGridTabPage)

			BEGIN_CLASS_MEMBER(::Smbios::DataGridTabPageConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::Smbios::DataGridTabPageConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_Smbios_DataGridTabPage_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_11)
				CLASS_MEMBER_FIELD(__vwsn_precompile_12)
				CLASS_MEMBER_FIELD(__vwsn_precompile_13)
				CLASS_MEMBER_FIELD(__vwsn_precompile_14)
				CLASS_MEMBER_FIELD(__vwsn_precompile_15)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(comboView)
				CLASS_MEMBER_FIELD(listView)
				CLASS_MEMBER_FIELD(self)
				CLASS_MEMBER_FIELD(textList)
			END_CLASS_MEMBER(::Smbios::DataGridTabPageConstructor)

			BEGIN_CLASS_MEMBER(::Smbios::DisplayDataToSmbiosData)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::Smbios::DisplayDataToSmbiosData>(), NO_PARAMETER)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::Smbios::DisplayDataToSmbiosData>(const ::vl::WString&, const ::vl::WString&, ::vl::vint, const ::vl::WString&), { L"desc" _ L"display" _ L"smbios_type" _ L"value" })
				CLASS_MEMBER_METHOD(GetDesc, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetDisplay, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetSmbiosType, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetSmbiosTypeValue, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetDesc, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetDisplay, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetSmbiosType, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetSmbiosTypeValue, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(SmbiosTypeChanged)
				CLASS_MEMBER_FIELD(__vwsn_prop_Desc)
				CLASS_MEMBER_FIELD(__vwsn_prop_Display)
				CLASS_MEMBER_FIELD(__vwsn_prop_SmbiosType)
				CLASS_MEMBER_FIELD(__vwsn_prop_SmbiosTypeValue)
				CLASS_MEMBER_PROPERTY(Desc, GetDesc, SetDesc)
				CLASS_MEMBER_PROPERTY(Display, GetDisplay, SetDisplay)
				CLASS_MEMBER_PROPERTY_EVENT(SmbiosType, GetSmbiosType, SetSmbiosType, SmbiosTypeChanged)
				CLASS_MEMBER_PROPERTY(SmbiosTypeValue, GetSmbiosTypeValue, SetSmbiosTypeValue)
			END_CLASS_MEMBER(::Smbios::DisplayDataToSmbiosData)

			BEGIN_CLASS_MEMBER(::Smbios::MainWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_BASE(::Smbios::MainWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::Smbios::MainWindow*(), NO_PARAMETER)
			END_CLASS_MEMBER(::Smbios::MainWindow)

			BEGIN_CLASS_MEMBER(::Smbios::MainWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::Smbios::MainWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_Smbios_MainWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::Smbios::MainWindowConstructor)

			BEGIN_CLASS_MEMBER(::Smbios::ProductInfoPage)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiTabPage)
				CLASS_MEMBER_BASE(::Smbios::ProductInfoPageConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::Smbios::ProductInfoPage*(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_instance_ctor_, NO_PARAMETER)
			END_CLASS_MEMBER(::Smbios::ProductInfoPage)

			BEGIN_CLASS_MEMBER(::Smbios::ProductInfoPageConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::Smbios::ProductInfoPageConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_Smbios_ProductInfoPage_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_11)
				CLASS_MEMBER_FIELD(__vwsn_precompile_12)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(comboView)
				CLASS_MEMBER_FIELD(listView)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::Smbios::ProductInfoPageConstructor)

			BEGIN_CLASS_MEMBER(::Smbios::SmbiosTypaDataItem)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::Smbios::SmbiosTypaDataItem>(), NO_PARAMETER)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::Smbios::SmbiosTypaDataItem>(::vl::vint, const ::vl::WString&, ::vl::vint64_t), { L"smbios_type" _ L"desc" _ L"addr" })
				CLASS_MEMBER_METHOD(GetAddress, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetDesc, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetType, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetAddress, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetDesc, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetType, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(AddressChanged)
				CLASS_MEMBER_EVENT(TypeChanged)
				CLASS_MEMBER_FIELD(__vwsn_prop_Address)
				CLASS_MEMBER_FIELD(__vwsn_prop_Desc)
				CLASS_MEMBER_FIELD(__vwsn_prop_Type)
				CLASS_MEMBER_PROPERTY_EVENT(Address, GetAddress, SetAddress, AddressChanged)
				CLASS_MEMBER_PROPERTY(Desc, GetDesc, SetDesc)
				CLASS_MEMBER_PROPERTY_EVENT(Type, GetType, SetType, TypeChanged)
			END_CLASS_MEMBER(::Smbios::SmbiosTypaDataItem)

#undef _
			class SmbiosTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::Smbios::DataGridTabPage)
					ADD_TYPE_INFO(::Smbios::DataGridTabPageConstructor)
					ADD_TYPE_INFO(::Smbios::DisplayDataToSmbiosData)
					ADD_TYPE_INFO(::Smbios::MainWindow)
					ADD_TYPE_INFO(::Smbios::MainWindowConstructor)
					ADD_TYPE_INFO(::Smbios::ProductInfoPage)
					ADD_TYPE_INFO(::Smbios::ProductInfoPageConstructor)
					ADD_TYPE_INFO(::Smbios::SmbiosTypaDataItem)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadSmbiosTypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new SmbiosTypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
