/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe MainWindow.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_SMBIOSREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_SMBIOSREFLECTION

#include "Smbios.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::Smbios::DataGridTabPage)
			DECL_TYPE_INFO(::Smbios::DataGridTabPageConstructor)
			DECL_TYPE_INFO(::Smbios::DisplayDataToSmbiosData)
			DECL_TYPE_INFO(::Smbios::MainWindow)
			DECL_TYPE_INFO(::Smbios::MainWindowConstructor)
			DECL_TYPE_INFO(::Smbios::ProductInfoPage)
			DECL_TYPE_INFO(::Smbios::ProductInfoPageConstructor)
			DECL_TYPE_INFO(::Smbios::SmbiosTypaDataItem)
			DECL_TYPE_INFO(::Smbios::TextEditor)
			DECL_TYPE_INFO(::Smbios::TextEditorConstructor)
#endif

			extern bool LoadSmbiosTypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif

#endif
