/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe MainWindow.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "Smbios.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, SmbiosReflection.h) */
#include "SmbiosReflection.h"
#endif
/* CodePack:EndIgnore() */

#include "..\..\..\libSmbios\LenovoDisplay.h"
#include "..\..\..\libSmbios\LibSMBIOS.h"
#include "..\..\TypeAll.hpp"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::Smbios::
#define GLOBAL_NAME ::vl_workflow_global::Smbios::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::Smbios::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_Smbios)
vl_workflow_global::Smbios instance;
INITIALIZE_GLOBAL_STORAGE_CLASS
FINALIZE_GLOBAL_STORAGE_CLASS
END_GLOBAL_STORAGE_CLASS(vl_workflow_global_Smbios)

namespace vl_workflow_global
{
	/***********************************************************************
	Global Functions
	***********************************************************************/

	Smbios& Smbios::Instance()
	{
		return Getvl_workflow_global_Smbios().instance;
	}

	/***********************************************************************
	Closures
	***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::reflection::description::Value __vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		if (__vwsn_update_)
		{
			::vl::__vwsn::This(itemToBind.Obj())->SetDesc(::vl::__vwsn::Unbox<::vl::WString>(__vwsn_value_));
			return ::vl::reflection::description::Value();
		}
		else
		{
			return ::vl::__vwsn::Box(::vl::__vwsn::This(itemToBind.Obj())->GetDesc());
		}
	}

	//-------------------------------------------------------------------

	__vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::WString __vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		return ::vl::__vwsn::This(itemToBind.Obj())->GetDesc();
	}

	//-------------------------------------------------------------------

	__vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::reflection::description::Value __vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		if (__vwsn_update_)
		{
			::vl::__vwsn::This(itemToBind.Obj())->SetDisplay(::vl::__vwsn::Unbox<::vl::WString>(__vwsn_value_));
			return ::vl::reflection::description::Value();
		}
		else
		{
			return ::vl::__vwsn::Box(::vl::__vwsn::This(itemToBind.Obj())->GetDisplay());
		}
	}

	//-------------------------------------------------------------------

	__vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::WString __vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		return ::vl::__vwsn::This(itemToBind.Obj())->GetDisplay();
	}

	//-------------------------------------------------------------------

	__vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::reflection::description::Value __vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		if (__vwsn_update_)
		{
			::vl::__vwsn::This(itemToBind.Obj())->SetSmbiosType(::vl::__vwsn::Unbox<::vl::vint>(__vwsn_value_));
			return ::vl::reflection::description::Value();
		}
		else
		{
			return ::vl::__vwsn::Box(::vl::__vwsn::This(itemToBind.Obj())->GetSmbiosType());
		}
	}

	//-------------------------------------------------------------------

	__vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::WString __vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		return ::vl::__vwsn::ToString(::vl::__vwsn::This(itemToBind.Obj())->GetSmbiosType());
	}

	//-------------------------------------------------------------------

	__vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::reflection::description::Value __vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		if (__vwsn_update_)
		{
			::vl::__vwsn::This(itemToBind.Obj())->SetSmbiosTypeValue(::vl::__vwsn::Unbox<::vl::WString>(__vwsn_value_));
			return ::vl::reflection::description::Value();
		}
		else
		{
			return ::vl::__vwsn::Box(::vl::__vwsn::This(itemToBind.Obj())->GetSmbiosTypeValue());
		}
	}

	//-------------------------------------------------------------------

	__vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::WString __vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_item_);
		return ::vl::__vwsn::This(itemToBind.Obj())->GetSmbiosTypeValue();
	}

	//-------------------------------------------------------------------

	__vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::__vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_::operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const
	{
		{
			auto __vwsn_switch_1 = ::vl::__vwsn::This(__vwsnthis_0->comboView)->GetSelectedIndex();
			if ((__vwsn_switch_1 == static_cast<::vl::vint>(0)))
			{
				::vl::__vwsn::This(__vwsnthis_0->listView)->SetView(::vl::presentation::controls::ListViewView::Tile);
			}
			else if ((__vwsn_switch_1 == static_cast<::vl::vint>(1)))
			{
				::vl::__vwsn::This(__vwsnthis_0->listView)->SetView(::vl::presentation::controls::ListViewView::Information);
			}
			else if ((__vwsn_switch_1 == static_cast<::vl::vint>(2)))
			{
				::vl::__vwsn::This(__vwsnthis_0->listView)->SetView(::vl::presentation::controls::ListViewView::Detail);
			}
		}
	}

	//-------------------------------------------------------------------

	__vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_::__vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_(::Smbios::TextEditorConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_value_) const
	{
		auto __vwsn_old_ = ::vl::__vwsn::This(__vwsnthis_0->textLabel)->GetText();
		auto __vwsn_new_ = ::vl::__vwsn::Unbox<::vl::WString>(__vwsn_value_);
		if ((__vwsn_old_ == __vwsn_new_))
		{
			return;
		}
		::vl::__vwsn::This(__vwsnthis_0->textLabel)->SetText(__vwsn_new_);
	}

	//-------------------------------------------------------------------

	__vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::__vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::reflection::description::Value __vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_item_);
		if (__vwsn_update_)
		{
			::vl::__vwsn::This(itemToBind.Obj())->SetType(::vl::__vwsn::Unbox<::vl::vint>(__vwsn_value_));
			return ::vl::reflection::description::Value();
		}
		else
		{
			return ::vl::__vwsn::Box(::vl::__vwsn::This(itemToBind.Obj())->GetType());
		}
	}

	//-------------------------------------------------------------------

	__vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::__vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::WString __vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_item_);
		return ::vl::__vwsn::ToString(::vl::__vwsn::This(itemToBind.Obj())->GetType());
	}

	//-------------------------------------------------------------------

	__vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::__vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::reflection::description::Value __vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_, const ::vl::reflection::description::Value& __vwsn_value_, bool __vwsn_update_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_item_);
		if (__vwsn_update_)
		{
			::vl::__vwsn::This(itemToBind.Obj())->SetDesc(::vl::__vwsn::Unbox<::vl::WString>(__vwsn_value_));
			return ::vl::reflection::description::Value();
		}
		else
		{
			return ::vl::__vwsn::Box(::vl::__vwsn::This(itemToBind.Obj())->GetDesc());
		}
	}

	//-------------------------------------------------------------------

	__vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::__vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::WString __vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_item_) const
	{
		auto itemToBind = ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_item_);
		return ::vl::__vwsn::This(itemToBind.Obj())->GetDesc();
	}

	//-------------------------------------------------------------------

	__vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::__vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const
	{
		{
			auto __vwsn_switch_0 = ::vl::__vwsn::This(__vwsnthis_0->comboView)->GetSelectedIndex();
			if ((__vwsn_switch_0 == static_cast<::vl::vint>(0)))
			{
				::vl::__vwsn::This(__vwsnthis_0->textList)->SetView(::vl::presentation::controls::ListViewView::Tile);
			}
			else if ((__vwsn_switch_0 == static_cast<::vl::vint>(1)))
			{
				::vl::__vwsn::This(__vwsnthis_0->textList)->SetView(::vl::presentation::controls::ListViewView::Information);
			}
			else if ((__vwsn_switch_0 == static_cast<::vl::vint>(2)))
			{
				::vl::__vwsn::This(__vwsnthis_0->textList)->SetView(::vl::presentation::controls::ListViewView::Detail);
			}
		}
	}

	//-------------------------------------------------------------------

	__vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::__vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
		, __vwsnthis_1(::vl::__vwsn::This(__vwsnctorthis_1))
	{
	}

	::vl::vint __vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const
	{
		return ::vl::reflection::description::Sys::Compare(::vl::__vwsn::This(__vwsno_1.Obj())->GetDisplay(), ::vl::__vwsn::This(__vwsno_2.Obj())->GetDisplay());
	}

	//-------------------------------------------------------------------

	__vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::__vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
		, __vwsnthis_1(::vl::__vwsn::This(__vwsnctorthis_1))
	{
	}

	::vl::vint __vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const
	{
		return ::vl::reflection::description::Sys::Compare(::vl::__vwsn::This(__vwsno_1.Obj())->GetSmbiosType(), ::vl::__vwsn::This(__vwsno_2.Obj())->GetSmbiosType());
	}

	//-------------------------------------------------------------------

	__vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::__vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
		, __vwsnthis_1(::vl::__vwsn::This(__vwsnctorthis_1))
	{
	}

	::vl::vint __vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const
	{
		return ::vl::reflection::description::Sys::Compare(::vl::__vwsn::This(__vwsno_1.Obj())->GetSmbiosTypeValue(), ::vl::__vwsn::This(__vwsno_2.Obj())->GetSmbiosTypeValue());
	}

	//-------------------------------------------------------------------

	__vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_::__vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::DataGridTabPageConstructor* __vwsnctorthis_1)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
		, __vwsnthis_1(::vl::__vwsn::This(__vwsnctorthis_1))
	{
	}

	::vl::vint __vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_::operator()(::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_1, ::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_2) const
	{
		return ::vl::reflection::description::Sys::Compare(::vl::__vwsn::This(__vwsno_1.Obj())->GetType(), ::vl::__vwsn::This(__vwsno_2.Obj())->GetType());
	}

	//-------------------------------------------------------------------

	__vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_::__vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::DataGridTabPageConstructor* __vwsnctorthis_1)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
		, __vwsnthis_1(::vl::__vwsn::This(__vwsnctorthis_1))
	{
	}

	::vl::vint __vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_::operator()(::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_1, ::vl::Ptr<::Smbios::SmbiosTypaDataItem> __vwsno_2) const
	{
		return ::vl::reflection::description::Sys::Compare(::vl::__vwsn::This(__vwsno_1.Obj())->GetDesc(), ::vl::__vwsn::This(__vwsno_2.Obj())->GetDesc());
	}

	//-------------------------------------------------------------------

	__vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::__vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(::Smbios::DataGridTabPage* __vwsnctor___vwsn_this_, ::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsn_this_(__vwsnctor___vwsn_this_)
		, __vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_::operator()(::vl::presentation::compositions::GuiGraphicsComposition* __vwsno_1, ::vl::presentation::compositions::GuiEventArgs* __vwsno_2) const
	{
		return ::vl::__vwsn::This(__vwsn_this_)->ListView_Selection_Changed(__vwsno_1, __vwsno_2);
	}

	//-------------------------------------------------------------------

	__vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::__vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(::vl::presentation::controls::list::IDataSorter* __vwsnctorthis_0, ::Smbios::ProductInfoPageConstructor* __vwsnctorthis_1)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
		, __vwsnthis_1(::vl::__vwsn::This(__vwsnctorthis_1))
	{
	}

	::vl::vint __vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_::operator()(::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_1, ::vl::Ptr<::Smbios::DisplayDataToSmbiosData> __vwsno_2) const
	{
		return ::vl::reflection::description::Sys::Compare(::vl::__vwsn::This(__vwsno_1.Obj())->GetDesc(), ::vl::__vwsn::This(__vwsno_2.Obj())->GetDesc());
	}

	//-------------------------------------------------------------------

	__vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter::__vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter::SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value)
	{
	}

	::vl::vint __vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter::Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_)
	{
		return LAMBDA(::vl_workflow_global::__vwsno1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_(this, __vwsnthis_0))(::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_row1_), ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_row2_));
	}

	//-------------------------------------------------------------------

	__vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter::__vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::DataGridTabPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter::SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value)
	{
	}

	::vl::vint __vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter::Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_)
	{
		return LAMBDA(::vl_workflow_global::__vwsno4_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_Compare_(this, __vwsnthis_0))(::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_row1_), ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::SmbiosTypaDataItem>>(__vwsn_row2_));
	}

	//-------------------------------------------------------------------

	__vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::__vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value)
	{
	}

	::vl::vint __vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_)
	{
		return LAMBDA(::vl_workflow_global::__vwsno9_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(this, __vwsnthis_0))(::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row1_), ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row2_));
	}

	//-------------------------------------------------------------------

	__vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::__vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value)
	{
	}

	::vl::vint __vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_)
	{
		return LAMBDA(::vl_workflow_global::__vwsno12_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(this, __vwsnthis_0))(::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row1_), ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row2_));
	}

	//-------------------------------------------------------------------

	__vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::__vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value)
	{
	}

	::vl::vint __vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_)
	{
		return LAMBDA(::vl_workflow_global::__vwsno15_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(this, __vwsnthis_0))(::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row1_), ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row2_));
	}

	//-------------------------------------------------------------------

	__vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::__vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(::Smbios::ProductInfoPageConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::SetCallback(::vl::presentation::controls::list::IDataProcessorCallback* value)
	{
	}

	::vl::vint __vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter::Compare(const ::vl::reflection::description::Value& __vwsn_row1_, const ::vl::reflection::description::Value& __vwsn_row2_)
	{
		return LAMBDA(::vl_workflow_global::__vwsno18_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_Compare_(this, __vwsnthis_0))(::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row1_), ::vl::__vwsn::Unbox<::vl::Ptr<::Smbios::DisplayDataToSmbiosData>>(__vwsn_row2_));
	}

	//-------------------------------------------------------------------

	__vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription(::Smbios::TextEditorConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
		this->__vwsn_bind_cache_0 = static_cast<::Smbios::TextEditor*>(nullptr);
		this->__vwsn_bind_handler_0_0 = ::vl::Ptr<::vl::reflection::description::IEventHandler>();
		this->__vwsn_bind_opened_ = false;
		this->__vwsn_bind_closed_ = false;
	}

	void __vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsn_bind_activator_()
	{
		auto __vwsn_bind_activator_result_ = [&]() { try { return ::vl::__vwsn::Unbox<::vl::WString>(::vl::__vwsn::This(__vwsn_bind_cache_0)->GetCellValue()); } catch (...) { return ::vl::WString(L"", false); } }();
		::vl::__vwsn::EventInvoke(this->ValueChanged)(::vl::__vwsn::Box(__vwsn_bind_activator_result_));
	}

	void __vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsn_bind_callback_0_0(::vl::presentation::compositions::GuiGraphicsComposition* __vwsn_bind_callback_argument_0, ::vl::presentation::compositions::GuiEventArgs* __vwsn_bind_callback_argument_1)
	{
		this->__vwsn_bind_activator_();
	}

	bool __vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::Open()
	{
		if ((!__vwsn_bind_opened_))
		{
			(__vwsn_bind_opened_ = true);
			(__vwsn_bind_cache_0 = [&]() { try { return __vwsnthis_0->self; } catch (...) { return static_cast<::Smbios::TextEditor*>(nullptr); } }());
			(__vwsn_bind_handler_0_0 = [&]() { try { return ::vl::__vwsn::EventAttach(::vl::__vwsn::This(__vwsn_bind_cache_0)->CellValueChanged, ::vl::Func<void(::vl::presentation::compositions::GuiGraphicsComposition*, ::vl::presentation::compositions::GuiEventArgs*)>(this, &__vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsn_bind_callback_0_0)); } catch (...) { return ::vl::Ptr<::vl::reflection::description::IEventHandler>(); } }());
			return true;
		}
		return false;
	}

	bool __vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::Update()
	{
		if ((__vwsn_bind_opened_ && (!__vwsn_bind_closed_)))
		{
			this->__vwsn_bind_activator_();
			return true;
		}
		return false;
	}

	bool __vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::Close()
	{
		if ((!__vwsn_bind_closed_))
		{
			(__vwsn_bind_closed_ = true);
			if (static_cast<bool>(__vwsn_bind_handler_0_0))
			{
				::vl::__vwsn::EventDetach(::vl::__vwsn::This(__vwsn_bind_cache_0)->CellValueChanged, __vwsn_bind_handler_0_0);
				(__vwsn_bind_handler_0_0 = ::vl::Ptr<::vl::reflection::description::IEventHandler>());
			}
			(__vwsn_bind_cache_0 = static_cast<::Smbios::TextEditor*>(nullptr));
			(__vwsn_bind_handler_0_0 = ::vl::Ptr<::vl::reflection::description::IEventHandler>());
			return true;
		}
		return false;
	}

	//-------------------------------------------------------------------

	__vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription(::Smbios::TextEditorConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
		this->__vwsn_bind_cache_0 = static_cast<::vl::presentation::controls::GuiLabel*>(nullptr);
		this->__vwsn_bind_handler_0_0 = ::vl::Ptr<::vl::reflection::description::IEventHandler>();
		this->__vwsn_bind_opened_ = false;
		this->__vwsn_bind_closed_ = false;
	}

	void __vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsn_bind_activator_()
	{
		auto __vwsn_bind_activator_result_ = ::vl::__vwsn::Box(::vl::__vwsn::This(__vwsn_bind_cache_0)->GetText());
		::vl::__vwsn::EventInvoke(this->ValueChanged)(__vwsn_bind_activator_result_);
	}

	void __vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsn_bind_callback_0_0(::vl::presentation::compositions::GuiGraphicsComposition* __vwsn_bind_callback_argument_0, ::vl::presentation::compositions::GuiEventArgs* __vwsn_bind_callback_argument_1)
	{
		this->__vwsn_bind_activator_();
	}

	bool __vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::Open()
	{
		if ((!__vwsn_bind_opened_))
		{
			(__vwsn_bind_opened_ = true);
			(__vwsn_bind_cache_0 = [&]() { try { return __vwsnthis_0->textLabel; } catch (...) { return static_cast<::vl::presentation::controls::GuiLabel*>(nullptr); } }());
			(__vwsn_bind_handler_0_0 = [&]() { try { return ::vl::__vwsn::EventAttach(::vl::__vwsn::This(__vwsn_bind_cache_0)->TextChanged, ::vl::Func<void(::vl::presentation::compositions::GuiGraphicsComposition*, ::vl::presentation::compositions::GuiEventArgs*)>(this, &__vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::__vwsn_bind_callback_0_0)); } catch (...) { return ::vl::Ptr<::vl::reflection::description::IEventHandler>(); } }());
			return true;
		}
		return false;
	}

	bool __vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::Update()
	{
		if ((__vwsn_bind_opened_ && (!__vwsn_bind_closed_)))
		{
			this->__vwsn_bind_activator_();
			return true;
		}
		return false;
	}

	bool __vwsnc8_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription::Close()
	{
		if ((!__vwsn_bind_closed_))
		{
			(__vwsn_bind_closed_ = true);
			if (static_cast<bool>(__vwsn_bind_handler_0_0))
			{
				::vl::__vwsn::EventDetach(::vl::__vwsn::This(__vwsn_bind_cache_0)->TextChanged, __vwsn_bind_handler_0_0);
				(__vwsn_bind_handler_0_0 = ::vl::Ptr<::vl::reflection::description::IEventHandler>());
			}
			(__vwsn_bind_cache_0 = static_cast<::vl::presentation::controls::GuiLabel*>(nullptr));
			(__vwsn_bind_handler_0_0 = ::vl::Ptr<::vl::reflection::description::IEventHandler>());
			return true;
		}
		return false;
	}
}

/***********************************************************************
Class (::Smbios::DataGridTabPageConstructor)
***********************************************************************/

namespace Smbios
{
	void DataGridTabPageConstructor::__vwsn_Smbios_DataGridTabPage_Initialize(::Smbios::DataGridTabPage* __vwsn_this_)
	{
		(this->self = __vwsn_this_);
		{
			::vl::__vwsn::This(this->self)->SetText(::vl::WString(L"Smbios信息", false));
		}
		(this->__vwsn_precompile_0 = new ::vl::presentation::compositions::GuiTableComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetCellPadding(static_cast<::vl::vint>(5));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetAlignmentToParent([&]() { ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(0); __vwsn_temp__.top = static_cast<::vl::vint>(0); __vwsn_temp__.right = static_cast<::vl::vint>(0); __vwsn_temp__.bottom = static_cast<::vl::vint>(0); return __vwsn_temp__; }());
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetRowsAndColumns(static_cast<::vl::vint>(2), static_cast<::vl::vint>(2));
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetRowOption(static_cast<::vl::vint>(0), [&]() { ::vl::presentation::compositions::GuiCellOption __vwsn_temp__; __vwsn_temp__.composeType = ::vl::presentation::compositions::GuiCellOption::ComposeType::MinSize; return __vwsn_temp__; }());
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetRowOption(static_cast<::vl::vint>(1), [&]() { ::vl::presentation::compositions::GuiCellOption __vwsn_temp__; __vwsn_temp__.composeType = ::vl::presentation::compositions::GuiCellOption::ComposeType::Percentage; __vwsn_temp__.percentage = static_cast<double>(1.0); return __vwsn_temp__; }());
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetColumnOption(static_cast<::vl::vint>(0), [&]() { ::vl::presentation::compositions::GuiCellOption __vwsn_temp__; __vwsn_temp__.composeType = ::vl::presentation::compositions::GuiCellOption::ComposeType::Absolute; __vwsn_temp__.absolute = static_cast<::vl::vint>(150); return __vwsn_temp__; }());
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetColumnOption(static_cast<::vl::vint>(1), [&]() { ::vl::presentation::compositions::GuiCellOption __vwsn_temp__; __vwsn_temp__.composeType = ::vl::presentation::compositions::GuiCellOption::ComposeType::Absolute; __vwsn_temp__.absolute = static_cast<::vl::vint>(150); return __vwsn_temp__; }());
		}
		(this->__vwsn_precompile_1 = new ::vl::presentation::compositions::GuiCellComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_1)->SetSite(static_cast<::vl::vint>(0), static_cast<::vl::vint>(0), static_cast<::vl::vint>(1), static_cast<::vl::vint>(2));
		}
		{
			(this->__vwsn_precompile_2 = new ::vl::presentation::controls::GuiTextList(::vl::presentation::theme::ThemeName::TextList));
		}
		(this->__vwsn_precompile_3 = ::vl::Ptr<::vl::presentation::controls::list::TextItem>(new ::vl::presentation::controls::list::TextItem()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_3.Obj())->SetText(::vl::WString(L"Tile", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->__vwsn_precompile_2)->GetItems());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_3));
		}
		(this->__vwsn_precompile_4 = ::vl::Ptr<::vl::presentation::controls::list::TextItem>(new ::vl::presentation::controls::list::TextItem()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_4.Obj())->SetText(::vl::WString(L"Information", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->__vwsn_precompile_2)->GetItems());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_4));
		}
		(this->__vwsn_precompile_5 = ::vl::Ptr<::vl::presentation::controls::list::TextItem>(new ::vl::presentation::controls::list::TextItem()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_5.Obj())->SetText(::vl::WString(L"Detail", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->__vwsn_precompile_2)->GetItems());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_5));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_2)->SetVerticalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_2)->SetHorizontalAlwaysVisible(false);
		}
		{
			(this->comboView = new ::vl::presentation::controls::GuiComboBoxListControl(::vl::presentation::theme::ThemeName::ComboBox, static_cast<::vl::presentation::controls::GuiSelectableListControl*>(this->__vwsn_precompile_2)));
		}
		{
			::vl::__vwsn::This(this->comboView)->SetSelectedIndex(static_cast<::vl::vint>(2));
		}
		{
			::vl::__vwsn::This(this->comboView)->SetAlt(::vl::WString(L"V", false));
		}
		(this->__vwsn_precompile_6 = ::vl::__vwsn::This(this->comboView)->GetBoundsComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_6)->SetPreferredMinSize([&]() { ::vl::presentation::Size __vwsn_temp__; __vwsn_temp__.x = static_cast<::vl::vint>(120); return __vwsn_temp__; }());
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_1)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(::vl::__vwsn::This(this->comboView)->GetBoundsComposition()));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_1));
		}
		(this->__vwsn_precompile_7 = new ::vl::presentation::compositions::GuiColumnSplitterComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_7)->SetColumnsToTheLeft(static_cast<::vl::vint>(1));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_7));
		}
		(this->__vwsn_precompile_8 = new ::vl::presentation::compositions::GuiCellComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_8)->SetSite(static_cast<::vl::vint>(1), static_cast<::vl::vint>(0), static_cast<::vl::vint>(1), static_cast<::vl::vint>(1));
		}
		{
			(this->listView = new ::vl::presentation::controls::GuiBindableDataGrid(::vl::presentation::theme::ThemeName::ListView));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetDataColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(static_cast<::vl::vint>(0)));
		}
		{
			::vl::__vwsn::This(this->listView)->SetVerticalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->listView)->SetHorizontalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->listView)->SetAlt(::vl::WString(L"L", false));
		}
		(this->__vwsn_precompile_11 = ::vl::__vwsn::This(this->listView)->GetBoundsComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_11)->SetAlignmentToParent([&]() { ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(0); __vwsn_temp__.top = static_cast<::vl::vint>(0); __vwsn_temp__.right = static_cast<::vl::vint>(0); __vwsn_temp__.bottom = static_cast<::vl::vint>(0); return __vwsn_temp__; }());
		}
		(this->__vwsn_precompile_9 = ::vl::Ptr<::vl::presentation::controls::list::DataColumn>(new ::vl::presentation::controls::list::DataColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetSorter(::vl::Ptr<::vl::presentation::controls::list::IDataSorter>(new ::vl_workflow_global::__vwsnc1_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetValueProperty(LAMBDA(::vl_workflow_global::__vwsnf2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetTextProperty(LAMBDA(::vl_workflow_global::__vwsnf3_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetSize(static_cast<::vl::vint>(60));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetText(::vl::WString(L"Type", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_9));
		}
		(this->__vwsn_precompile_10 = ::vl::Ptr<::vl::presentation::controls::list::DataColumn>(new ::vl::presentation::controls::list::DataColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetSorter(::vl::Ptr<::vl::presentation::controls::list::IDataSorter>(new ::vl_workflow_global::__vwsnc2_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize__vl_presentation_controls_list_IDataSorter(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetValueProperty(LAMBDA(::vl_workflow_global::__vwsnf5_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetTextProperty(LAMBDA(::vl_workflow_global::__vwsnf6_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetSize(static_cast<::vl::vint>(120));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetText(::vl::WString(L"描述", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_10));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_8)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(::vl::__vwsn::This(this->listView)->GetBoundsComposition()));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_8));
		}
		(this->__vwsn_precompile_12 = new ::vl::presentation::compositions::GuiCellComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_12)->SetSite(static_cast<::vl::vint>(1), static_cast<::vl::vint>(1), static_cast<::vl::vint>(1), static_cast<::vl::vint>(1));
		}
		{
			(this->textList = new ::vl::presentation::controls::GuiListView(::vl::presentation::theme::ThemeName::ListView));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->textList)->GetDataColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(static_cast<::vl::vint>(0)));
		}
		{
			::vl::__vwsn::This(this->textList)->SetVerticalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->textList)->SetHorizontalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->textList)->SetAlt(::vl::WString(L"T", false));
		}
		(this->__vwsn_precompile_15 = ::vl::__vwsn::This(this->textList)->GetBoundsComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_15)->SetAlignmentToParent([&]() { ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(0); __vwsn_temp__.top = static_cast<::vl::vint>(0); __vwsn_temp__.right = static_cast<::vl::vint>(0); __vwsn_temp__.bottom = static_cast<::vl::vint>(0); return __vwsn_temp__; }());
		}
		(this->__vwsn_precompile_13 = ::vl::Ptr<::vl::presentation::controls::list::ListViewColumn>(new ::vl::presentation::controls::list::ListViewColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_13.Obj())->SetSize(static_cast<::vl::vint>(60));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_13.Obj())->SetText(::vl::WString(L"名称", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->textList)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_13));
		}
		(this->__vwsn_precompile_14 = ::vl::Ptr<::vl::presentation::controls::list::ListViewColumn>(new ::vl::presentation::controls::list::ListViewColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_14.Obj())->SetText(::vl::WString(L"信息", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->textList)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_14));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_12)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(::vl::__vwsn::This(this->textList)->GetBoundsComposition()));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_12));
		}
		{
			::vl::__vwsn::This(::vl::__vwsn::This(this->self)->GetContainerComposition())->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_0));
		}
		{
			auto __vwsn_event_handler_ = LAMBDA(::vl_workflow_global::__vwsnf7_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(this));
			::vl::__vwsn::EventAttach(::vl::__vwsn::This(this->comboView)->SelectedIndexChanged, __vwsn_event_handler_);
		}
		{
			::vl::__vwsn::EventAttach(::vl::__vwsn::This(this->listView)->SelectionChanged, LAMBDA(::vl_workflow_global::__vwsno8_Smbios_Smbios_DataGridTabPageConstructor___vwsn_Smbios_DataGridTabPage_Initialize_(__vwsn_this_, this)));
		}
	}

	DataGridTabPageConstructor::DataGridTabPageConstructor()
		: self(static_cast<::Smbios::DataGridTabPage*>(nullptr))
		, comboView(static_cast<::vl::presentation::controls::GuiComboBoxListControl*>(nullptr))
		, listView(static_cast<::vl::presentation::controls::GuiBindableDataGrid*>(nullptr))
		, textList(static_cast<::vl::presentation::controls::GuiListView*>(nullptr))
		, __vwsn_precompile_0(static_cast<::vl::presentation::compositions::GuiTableComposition*>(nullptr))
		, __vwsn_precompile_1(static_cast<::vl::presentation::compositions::GuiCellComposition*>(nullptr))
		, __vwsn_precompile_2(static_cast<::vl::presentation::controls::GuiTextList*>(nullptr))
		, __vwsn_precompile_3(::vl::Ptr<::vl::presentation::controls::list::TextItem>())
		, __vwsn_precompile_4(::vl::Ptr<::vl::presentation::controls::list::TextItem>())
		, __vwsn_precompile_5(::vl::Ptr<::vl::presentation::controls::list::TextItem>())
		, __vwsn_precompile_6(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
		, __vwsn_precompile_7(static_cast<::vl::presentation::compositions::GuiColumnSplitterComposition*>(nullptr))
		, __vwsn_precompile_8(static_cast<::vl::presentation::compositions::GuiCellComposition*>(nullptr))
		, __vwsn_precompile_9(::vl::Ptr<::vl::presentation::controls::list::DataColumn>())
		, __vwsn_precompile_10(::vl::Ptr<::vl::presentation::controls::list::DataColumn>())
		, __vwsn_precompile_11(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
		, __vwsn_precompile_12(static_cast<::vl::presentation::compositions::GuiCellComposition*>(nullptr))
		, __vwsn_precompile_13(::vl::Ptr<::vl::presentation::controls::list::ListViewColumn>())
		, __vwsn_precompile_14(::vl::Ptr<::vl::presentation::controls::list::ListViewColumn>())
		, __vwsn_precompile_15(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
	{
	}

	/***********************************************************************
	Class (::Smbios::DataGridTabPage)
	***********************************************************************/

	void DataGridTabPage::ListView_Selection_Changed(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments)
	{/* USER_CONTENT_BEGIN(::Smbios::DataGridTabPage) */
		CreateTextlistData();
	}/* USER_CONTENT_END() */

	DataGridTabPage::DataGridTabPage()
		: ::vl::presentation::controls::GuiTabPage(::vl::presentation::theme::ThemeName::CustomControl)
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString(L"Smbios::DataGridTabPage", false));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_Smbios_DataGridTabPage_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void DataGridTabPage::__vwsn_instance_ctor_()
	{
		/* USER_CONTENT_BEGIN(::Smbios::DataGridTabPage) */
		TypeFunctions =
		{
			{0,Smbios::Display::Type0ToTextList},
			{1,Smbios::Display::Type1ToTextList},
			{2,Smbios::Display::Type2ToTextList},
			{3,Smbios::Display::Type3ToTextList},
			{4,Smbios::Display::Type4ToTextList},
			{5,Smbios::Display::Type5ToTextList},
			{6,Smbios::Display::Type6ToTextList},
			{7,Smbios::Display::Type7ToTextList},
			{8,Smbios::Display::Type8ToTextList},
			{9,Smbios::Display::Type9ToTextList},
			{10,Smbios::Display::Type10ToTextList},
			{11,Smbios::Display::Type11ToTextList},
			{12,Smbios::Display::Type12ToTextList},
			{13,Smbios::Display::Type13ToTextList},
			{14,Smbios::Display::Type14ToTextList},
			{15,Smbios::Display::Type15ToTextList},
			{16,Smbios::Display::Type16ToTextList},
			{17,Smbios::Display::Type17ToTextList},
			{18,Smbios::Display::Type18ToTextList},
			{19,Smbios::Display::Type19ToTextList},
			{20,Smbios::Display::Type20ToTextList},
			{21,Smbios::Display::Type21ToTextList},
			{22,Smbios::Display::Type22ToTextList},
			{23,Smbios::Display::Type23ToTextList},
			{24,Smbios::Display::Type24ToTextList},
			{25,Smbios::Display::Type25ToTextList},
			{26,Smbios::Display::Type26ToTextList},
			{27,Smbios::Display::Type27ToTextList},
			{28,Smbios::Display::Type28ToTextList},
			{29,Smbios::Display::Type29ToTextList},
			{30,Smbios::Display::Type30ToTextList},
			{32,Smbios::Display::Type32ToTextList},
			{33,Smbios::Display::Type33ToTextList},
			{34,Smbios::Display::Type34ToTextList},
			{35,Smbios::Display::Type35ToTextList},
			{36,Smbios::Display::Type36ToTextList},
			{37,Smbios::Display::Type37ToTextList},
			{38,Smbios::Display::Type38ToTextList},
			{39,Smbios::Display::Type39ToTextList},
			{40,Smbios::Display::Type40ToTextList},
			{41,Smbios::Display::Type41ToTextList},
			{42,Smbios::Display::Type42ToTextList},
			{43,Smbios::Display::Type43ToTextList},
			{44,Smbios::Display::Type44ToTextList},
		};

		try
		{
			Vendor = Smbios::GetType(SmbiosHeaderType::Type1()).Manufacturer();
		}
		catch (const std::exception&)
		{
		}
		auto tempData = ::vl::__vwsn::CreateObservableList();
		auto Types = Smbios::GetAllTypes();
		for (const auto& Type : Types)
		{
			tempData.Add(vl::MakePtr<SmbiosTypaDataItem>(Type->GetHeader().type, Type->Descriptor().c_str(), reinterpret_cast<vl::vint64_t>(Type->GetVirtualBaseAddress())));
		}
		::vl::__vwsn::This(this->listView)->SetItemSource(::vl::Ptr<::vl::reflection::description::IValueEnumerable>(tempData.list));
		/* USER_CONTENT_END() */
	}

	DataGridTabPage::~DataGridTabPage()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::controls::GuiCustomControl*>(this));
	}

	/* USER_CONTENT_BEGIN(::Smbios::DataGridTabPage) */
	void DataGridTabPage::CreateTextlistData()
	{
		auto Value = ::vl::reflection::description::UnboxValue<::vl::Ptr<SmbiosTypaDataItem>>(listView->GetSelectedRowValue());
		if (!Value)
		{
			return;
		}

		textList->GetItems().Clear();
		Smbios::DMI_Header* Dmi = reinterpret_cast<Smbios::DMI_Header*>(Value->GetAddress());
		decltype(auto) Items = textList->GetItems();
		{
			auto Item = new ::vl::presentation::controls::list::ListViewItem();
			Item->SetText(L"Type");
			decltype(auto) SubItems = Item->GetSubItems();
			std::wostringstream oss;
			oss << std::dec << Dmi->type;
			SubItems.Add(oss.str().c_str());
			Items.Add(Item);
		}

		{
			auto Item = new ::vl::presentation::controls::list::ListViewItem();
			Item->SetText(L"Length");
			decltype(auto) SubItems = Item->GetSubItems();
			std::wostringstream oss;
			oss << std::dec << Dmi->length;
			SubItems.Add(oss.str().c_str());
			Items.Add(Item);
		}

		{
			auto Item = new ::vl::presentation::controls::list::ListViewItem();
			Item->SetText(L"Handle");
			decltype(auto) SubItems = Item->GetSubItems();
			std::wostringstream oss;
			oss << std::dec << Dmi->handle;
			SubItems.Add(oss.str().c_str());
			Items.Add(Item);
		}

		auto itr = TypeFunctions.find(Dmi->type);
		if (itr != TypeFunctions.end())
		{
			itr->second(Dmi, textList);
		}
		else
		{
			if (!Vendor.empty())
			{
				if (Vendor == "Acer")
				{
				}
				else if (Vendor == "HP" || Vendor == "HPE" || Vendor == "Hewlett-Packard" || Vendor == "Hewlett Packard Enterprise")
				{
				}
				else if (Vendor == "IBM" || Vendor == "LENOVO")
				{
					switch (Dmi->type)
					{
					case 131:
						Smbios::Display::Type131_Lenovo_ToTextList(Dmi, textList);
						break;
					case 133:
						Smbios::Display::Type133_Lenovo_ToTextList(Dmi, textList);
						break;
					case 134:
						Smbios::Display::Type134_Lenovo_ToTextList(Dmi, textList);
						break;
					case 140:
						Smbios::Display::Type140_Lenovo_ToTextList(Dmi, textList);
						break;
					case 200:
						Smbios::Display::Type200_Lenovo_ToTextList(Dmi, textList);
						break;
					default:
						break;
					}
				}
			}
		}
	}
	/* USER_CONTENT_END() */

	/***********************************************************************
	Class (::Smbios::DisplayDataToSmbiosData)
	***********************************************************************/

	::vl::WString DisplayDataToSmbiosData::GetDesc()
	{
		return this->__vwsn_prop_Desc;
	}

	void DisplayDataToSmbiosData::SetDesc(const ::vl::WString& __vwsn_value_)
	{
		(this->__vwsn_prop_Desc = __vwsn_value_);
	}

	::vl::WString DisplayDataToSmbiosData::GetDisplay()
	{
		return this->__vwsn_prop_Display;
	}

	void DisplayDataToSmbiosData::SetDisplay(const ::vl::WString& __vwsn_value_)
	{
		(this->__vwsn_prop_Display = __vwsn_value_);
	}

	::vl::vint DisplayDataToSmbiosData::GetSmbiosType()
	{
		return this->__vwsn_prop_SmbiosType;
	}

	void DisplayDataToSmbiosData::SetSmbiosType(::vl::vint __vwsn_value_)
	{
		(this->__vwsn_prop_SmbiosType = __vwsn_value_);
	}

	::vl::WString DisplayDataToSmbiosData::GetSmbiosTypeValue()
	{
		return this->__vwsn_prop_SmbiosTypeValue;
	}

	void DisplayDataToSmbiosData::SetSmbiosTypeValue(const ::vl::WString& __vwsn_value_)
	{
		(this->__vwsn_prop_SmbiosTypeValue = __vwsn_value_);
	}

	DisplayDataToSmbiosData::DisplayDataToSmbiosData()
		: __vwsn_prop_Desc(::vl::WString(L"", false))
		, __vwsn_prop_Display(::vl::WString(L"", false))
		, __vwsn_prop_SmbiosType(static_cast<::vl::vint>(0))
		, __vwsn_prop_SmbiosTypeValue(::vl::WString(L"", false))
	{
	}

	DisplayDataToSmbiosData::DisplayDataToSmbiosData(const ::vl::WString& desc, const ::vl::WString& display, const ::vl::vint& type, const ::vl::WString& value)
		: __vwsn_prop_Desc(::vl::WString(L"", false))
		, __vwsn_prop_Display(::vl::WString(L"", false))
		, __vwsn_prop_SmbiosType(static_cast<::vl::vint>(0))
		, __vwsn_prop_SmbiosTypeValue(::vl::WString(L"", false))
	{
		this->SetDesc(desc);
		this->SetDisplay(display);
		this->SetSmbiosType(type);
		this->SetSmbiosTypeValue(value);
	}

	/***********************************************************************
	Class (::Smbios::MainWindowConstructor)
	***********************************************************************/

	void MainWindowConstructor::__vwsn_Smbios_MainWindow_Initialize(::Smbios::MainWindow* __vwsn_this_)
	{
		(this->self = __vwsn_this_);
		(this->__vwsn_precompile_4 = ::vl::__vwsn::This(this->self)->GetBoundsComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_4)->SetPreferredMinSize([&]() { ::vl::presentation::Size __vwsn_temp__; __vwsn_temp__.x = static_cast<::vl::vint>(640); __vwsn_temp__.y = static_cast<::vl::vint>(480); return __vwsn_temp__; }());
		}
		{
			::vl::__vwsn::This(this->self)->SetClientSize([&]() { ::vl::presentation::Size __vwsn_temp__; __vwsn_temp__.x = static_cast<::vl::vint>(640); __vwsn_temp__.y = static_cast<::vl::vint>(480); return __vwsn_temp__; }());
		}
		{
			::vl::__vwsn::This(this->self)->SetText(::vl::WString(L"SMBIOS", false));
		}
		{
			(this->__vwsn_precompile_0 = new ::vl::presentation::controls::GuiTab(::vl::presentation::theme::ThemeName::Tab));
		}
		(this->__vwsn_precompile_2 = new ::Smbios::DataGridTabPage());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_2)->SetAlt(::vl::WString(L"D", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueObservableList>(::vl::__vwsn::This(this->__vwsn_precompile_0)->GetPages());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_2));
		}
		(this->__vwsn_precompile_3 = new ::Smbios::ProductInfoPage());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_3)->SetAlt(::vl::WString(L"P", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueObservableList>(::vl::__vwsn::This(this->__vwsn_precompile_0)->GetPages());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_3));
		}
		(this->__vwsn_precompile_1 = ::vl::__vwsn::This(this->__vwsn_precompile_0)->GetBoundsComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_1)->SetAlignmentToParent([&]() { ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(5); __vwsn_temp__.top = static_cast<::vl::vint>(5); __vwsn_temp__.right = static_cast<::vl::vint>(5); __vwsn_temp__.bottom = static_cast<::vl::vint>(5); return __vwsn_temp__; }());
		}
		{
			::vl::__vwsn::This(this->self)->AddChild(static_cast<::vl::presentation::controls::GuiControl*>(this->__vwsn_precompile_0));
		}
	}

	MainWindowConstructor::MainWindowConstructor()
		: self(static_cast<::Smbios::MainWindow*>(nullptr))
		, __vwsn_precompile_0(static_cast<::vl::presentation::controls::GuiTab*>(nullptr))
		, __vwsn_precompile_1(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
		, __vwsn_precompile_2(static_cast<::Smbios::DataGridTabPage*>(nullptr))
		, __vwsn_precompile_3(static_cast<::Smbios::ProductInfoPage*>(nullptr))
		, __vwsn_precompile_4(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
	{
	}

	/***********************************************************************
	Class (::Smbios::MainWindow)
	***********************************************************************/

	MainWindow::MainWindow()
		: ::vl::presentation::controls::GuiWindow(::vl::presentation::theme::ThemeName::Window)
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString(L"Smbios::MainWindow", false));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_Smbios_MainWindow_Initialize(this);
	}

	MainWindow::~MainWindow()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::controls::GuiControlHost*>(this));
	}

	/***********************************************************************
	Class (::Smbios::ProductInfoPageConstructor)
	***********************************************************************/

	void ProductInfoPageConstructor::__vwsn_Smbios_ProductInfoPage_Initialize(::Smbios::ProductInfoPage* __vwsn_this_)
	{
		(this->self = __vwsn_this_);
		{
			::vl::__vwsn::This(this->self)->SetText(::vl::WString(L"联想电脑需要的BIOS信息", false));
		}
		(this->__vwsn_precompile_0 = new ::vl::presentation::compositions::GuiTableComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetCellPadding(static_cast<::vl::vint>(5));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetAlignmentToParent([&]() { ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(0); __vwsn_temp__.top = static_cast<::vl::vint>(0); __vwsn_temp__.right = static_cast<::vl::vint>(0); __vwsn_temp__.bottom = static_cast<::vl::vint>(0); return __vwsn_temp__; }());
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetRowsAndColumns(static_cast<::vl::vint>(2), static_cast<::vl::vint>(1));
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetRowOption(static_cast<::vl::vint>(0), [&]() { ::vl::presentation::compositions::GuiCellOption __vwsn_temp__; __vwsn_temp__.composeType = ::vl::presentation::compositions::GuiCellOption::ComposeType::MinSize; return __vwsn_temp__; }());
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetRowOption(static_cast<::vl::vint>(1), [&]() { ::vl::presentation::compositions::GuiCellOption __vwsn_temp__; __vwsn_temp__.composeType = ::vl::presentation::compositions::GuiCellOption::ComposeType::Percentage; __vwsn_temp__.percentage = static_cast<double>(1.0); return __vwsn_temp__; }());
			::vl::__vwsn::This(this->__vwsn_precompile_0)->SetColumnOption(static_cast<::vl::vint>(0), [&]() { ::vl::presentation::compositions::GuiCellOption __vwsn_temp__; __vwsn_temp__.composeType = ::vl::presentation::compositions::GuiCellOption::ComposeType::Percentage; __vwsn_temp__.percentage = static_cast<double>(1.0); return __vwsn_temp__; }());
		}
		(this->__vwsn_precompile_1 = new ::vl::presentation::compositions::GuiCellComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_1)->SetSite(static_cast<::vl::vint>(0), static_cast<::vl::vint>(0), static_cast<::vl::vint>(1), static_cast<::vl::vint>(1));
		}
		{
			(this->__vwsn_precompile_2 = new ::vl::presentation::controls::GuiTextList(::vl::presentation::theme::ThemeName::TextList));
		}
		(this->__vwsn_precompile_3 = ::vl::Ptr<::vl::presentation::controls::list::TextItem>(new ::vl::presentation::controls::list::TextItem()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_3.Obj())->SetText(::vl::WString(L"Tile", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->__vwsn_precompile_2)->GetItems());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_3));
		}
		(this->__vwsn_precompile_4 = ::vl::Ptr<::vl::presentation::controls::list::TextItem>(new ::vl::presentation::controls::list::TextItem()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_4.Obj())->SetText(::vl::WString(L"Information", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->__vwsn_precompile_2)->GetItems());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_4));
		}
		(this->__vwsn_precompile_5 = ::vl::Ptr<::vl::presentation::controls::list::TextItem>(new ::vl::presentation::controls::list::TextItem()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_5.Obj())->SetText(::vl::WString(L"Detail", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->__vwsn_precompile_2)->GetItems());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_5));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_2)->SetVerticalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_2)->SetHorizontalAlwaysVisible(false);
		}
		{
			(this->comboView = new ::vl::presentation::controls::GuiComboBoxListControl(::vl::presentation::theme::ThemeName::ComboBox, static_cast<::vl::presentation::controls::GuiSelectableListControl*>(this->__vwsn_precompile_2)));
		}
		{
			::vl::__vwsn::This(this->comboView)->SetSelectedIndex(static_cast<::vl::vint>(2));
		}
		{
			::vl::__vwsn::This(this->comboView)->SetAlt(::vl::WString(L"V", false));
		}
		(this->__vwsn_precompile_6 = ::vl::__vwsn::This(this->comboView)->GetBoundsComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_6)->SetPreferredMinSize([&]() { ::vl::presentation::Size __vwsn_temp__; __vwsn_temp__.x = static_cast<::vl::vint>(120); return __vwsn_temp__; }());
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_1)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(::vl::__vwsn::This(this->comboView)->GetBoundsComposition()));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_1));
		}
		(this->__vwsn_precompile_7 = new ::vl::presentation::compositions::GuiCellComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_7)->SetSite(static_cast<::vl::vint>(1), static_cast<::vl::vint>(0), static_cast<::vl::vint>(1), static_cast<::vl::vint>(1));
		}
		{
			(this->listView = new ::vl::presentation::controls::GuiBindableDataGrid(::vl::presentation::theme::ThemeName::ListView));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetDataColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(static_cast<::vl::vint>(0)));
		}
		{
			::vl::__vwsn::This(this->listView)->SetVerticalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->listView)->SetHorizontalAlwaysVisible(false);
		}
		{
			::vl::__vwsn::This(this->listView)->SetAlt(::vl::WString(L"L", false));
		}
		(this->__vwsn_precompile_12 = ::vl::__vwsn::This(this->listView)->GetBoundsComposition());
		{
			::vl::__vwsn::This(this->__vwsn_precompile_12)->SetAlignmentToParent([&]() { ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(0); __vwsn_temp__.top = static_cast<::vl::vint>(0); __vwsn_temp__.right = static_cast<::vl::vint>(0); __vwsn_temp__.bottom = static_cast<::vl::vint>(0); return __vwsn_temp__; }());
		}
		(this->__vwsn_precompile_8 = ::vl::Ptr<::vl::presentation::controls::list::DataColumn>(new ::vl::presentation::controls::list::DataColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_8.Obj())->SetSorter(::vl::Ptr<::vl::presentation::controls::list::IDataSorter>(new ::vl_workflow_global::__vwsnc3_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_8.Obj())->SetValueProperty(LAMBDA(::vl_workflow_global::__vwsnf10_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_8.Obj())->SetTextProperty(LAMBDA(::vl_workflow_global::__vwsnf11_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_8.Obj())->SetSize(static_cast<::vl::vint>(60));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_8.Obj())->SetText(::vl::WString(L"描述", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_8));
		}
		(this->__vwsn_precompile_9 = ::vl::Ptr<::vl::presentation::controls::list::DataColumn>(new ::vl::presentation::controls::list::DataColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetSorter(::vl::Ptr<::vl::presentation::controls::list::IDataSorter>(new ::vl_workflow_global::__vwsnc4_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetValueProperty(LAMBDA(::vl_workflow_global::__vwsnf13_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetTextProperty(LAMBDA(::vl_workflow_global::__vwsnf14_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetSize(static_cast<::vl::vint>(120));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_9.Obj())->SetText(::vl::WString(L"显示项", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_9));
		}
		(this->__vwsn_precompile_10 = ::vl::Ptr<::vl::presentation::controls::list::DataColumn>(new ::vl::presentation::controls::list::DataColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetSorter(::vl::Ptr<::vl::presentation::controls::list::IDataSorter>(new ::vl_workflow_global::__vwsnc5_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetValueProperty(LAMBDA(::vl_workflow_global::__vwsnf16_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetTextProperty(LAMBDA(::vl_workflow_global::__vwsnf17_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetSize(static_cast<::vl::vint>(120));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_10.Obj())->SetText(::vl::WString(L"对应SmbiosType", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_10));
		}
		(this->__vwsn_precompile_11 = ::vl::Ptr<::vl::presentation::controls::list::DataColumn>(new ::vl::presentation::controls::list::DataColumn()));
		{
			::vl::__vwsn::This(this->__vwsn_precompile_11.Obj())->SetSorter(::vl::Ptr<::vl::presentation::controls::list::IDataSorter>(new ::vl_workflow_global::__vwsnc6_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize__vl_presentation_controls_list_IDataSorter(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_11.Obj())->SetValueProperty(LAMBDA(::vl_workflow_global::__vwsnf19_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_11.Obj())->SetTextProperty(LAMBDA(::vl_workflow_global::__vwsnf20_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this)));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_11.Obj())->SetSize(static_cast<::vl::vint>(120));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_11.Obj())->SetText(::vl::WString(L"项名及项值", false));
		}
		{
			auto __vwsn_collection_ = ::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->listView)->GetColumns());
			::vl::__vwsn::This(__vwsn_collection_.Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_11));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_7)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(::vl::__vwsn::This(this->listView)->GetBoundsComposition()));
		}
		{
			::vl::__vwsn::This(this->__vwsn_precompile_0)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_7));
		}
		{
			::vl::__vwsn::This(::vl::__vwsn::This(this->self)->GetContainerComposition())->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->__vwsn_precompile_0));
		}
		{
			auto __vwsn_event_handler_ = LAMBDA(::vl_workflow_global::__vwsnf21_Smbios_Smbios_ProductInfoPageConstructor___vwsn_Smbios_ProductInfoPage_Initialize_(this));
			::vl::__vwsn::EventAttach(::vl::__vwsn::This(this->comboView)->SelectedIndexChanged, __vwsn_event_handler_);
		}
	}

	ProductInfoPageConstructor::ProductInfoPageConstructor()
		: self(static_cast<::Smbios::ProductInfoPage*>(nullptr))
		, comboView(static_cast<::vl::presentation::controls::GuiComboBoxListControl*>(nullptr))
		, listView(static_cast<::vl::presentation::controls::GuiBindableDataGrid*>(nullptr))
		, __vwsn_precompile_0(static_cast<::vl::presentation::compositions::GuiTableComposition*>(nullptr))
		, __vwsn_precompile_1(static_cast<::vl::presentation::compositions::GuiCellComposition*>(nullptr))
		, __vwsn_precompile_2(static_cast<::vl::presentation::controls::GuiTextList*>(nullptr))
		, __vwsn_precompile_3(::vl::Ptr<::vl::presentation::controls::list::TextItem>())
		, __vwsn_precompile_4(::vl::Ptr<::vl::presentation::controls::list::TextItem>())
		, __vwsn_precompile_5(::vl::Ptr<::vl::presentation::controls::list::TextItem>())
		, __vwsn_precompile_6(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
		, __vwsn_precompile_7(static_cast<::vl::presentation::compositions::GuiCellComposition*>(nullptr))
		, __vwsn_precompile_8(::vl::Ptr<::vl::presentation::controls::list::DataColumn>())
		, __vwsn_precompile_9(::vl::Ptr<::vl::presentation::controls::list::DataColumn>())
		, __vwsn_precompile_10(::vl::Ptr<::vl::presentation::controls::list::DataColumn>())
		, __vwsn_precompile_11(::vl::Ptr<::vl::presentation::controls::list::DataColumn>())
		, __vwsn_precompile_12(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
	{
	}

	/***********************************************************************
	Class (::Smbios::ProductInfoPage)
	***********************************************************************/

	ProductInfoPage::ProductInfoPage()
		: ::vl::presentation::controls::GuiTabPage(::vl::presentation::theme::ThemeName::CustomControl)
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString(L"Smbios::ProductInfoPage", false));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_Smbios_ProductInfoPage_Initialize(this);
		this->__vwsn_instance_ctor_();
	}

	void ProductInfoPage::__vwsn_instance_ctor_()
	{
		auto tempData = ::vl::__vwsn::CreateObservableList();
		if (Smbios::LenovoDisplay::IsLenovo())
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"机器名", Smbios::LenovoDisplay::GetMachineTypeFromSMbios().c_str(), 1, L"Version"));
		}
		else
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"机器名", Smbios::LenovoDisplay::GetMachineTypeFromSMbios().c_str(), 1, L"ProductName"));
		}

		tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"机器SN", Smbios::LenovoDisplay::GetSNFromSMbios().c_str(), 1, L"Serial Number"));
		if (Smbios::LenovoDisplay::IsLenovo())
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"机器MT", Smbios::LenovoDisplay::GetMachineType().c_str(), 1, L"ProductName"));
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"机器MTM", Smbios::LenovoDisplay::GetMachineTypeModel().c_str(), 200, L"MTM"));
		}
		tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"机器UUID", Smbios::LenovoDisplay::GetMachineUUID().c_str(), 1, L"UUID"));

		try
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"CPU", utf8ToWstring(Smbios::GetType(Smbios::SmbiosHeaderType::Type4()).at(0).ProcessorVersion()).c_str(), 4, L"Processor Version"));
		}
		catch (const std::exception&)
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"CPU", L"读取错误请检查SMbios", 4, L"Processor Version"));
		}

		try
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"CPU核心数", std::to_wstring(Smbios::GetType(Smbios::SmbiosHeaderType::Type4()).at(0).CoreCount()).c_str(), 4, L"Core Count"));
		}
		catch (const std::exception&)
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"CPU核心数", L"读取错误请检查SMbios", 4, L"Core Count"));
		}

		try
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"逻辑处理器个数", std::to_wstring(Smbios::GetType(Smbios::SmbiosHeaderType::Type4()).at(0).ThreadCount()).c_str(), 4, L"Thread Count"));
		}
		catch (const std::exception&)
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"逻辑处理器个数", L"读取错误请检查SMbios", 4, L"Thread Count"));
		}

		try
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"主频", utf8ToWstring(Smbios::GetType(Smbios::SmbiosHeaderType::Type4()).at(0).MaxSpeed()).c_str(), 4, L"Max Speed"));
		}
		catch (const std::exception&)
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"主频", L"读取错误请检查SMbios", 4, L"Max Speed"));
		}

		try
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"外频", utf8ToWstring(Smbios::GetType(Smbios::SmbiosHeaderType::Type4()).at(0).ExtClock()).c_str(), 4, L"External Clock"));
		}
		catch (const std::exception&)
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"外频", L"读取错误请检查SMbios", 4, L"External Clock"));
		}

		try
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"内存数量", std::to_wstring(Smbios::GetType(Smbios::SmbiosHeaderType::Type17()).size()).c_str(), 17, L"Type17 Numbers"));
		}
		catch (const std::exception&)
		{
			tempData.Add(vl::MakePtr<DisplayDataToSmbiosData>(L"内存数量", L"读取错误请检查SMbios", 17, L"Type17 Numbers"));
		}

		::vl::__vwsn::This(this->listView)->SetItemSource(::vl::Ptr<::vl::reflection::description::IValueEnumerable>(tempData.list));
	}

	ProductInfoPage::~ProductInfoPage()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::controls::GuiCustomControl*>(this));
	}

	/***********************************************************************
	Class (::Smbios::SmbiosTypaDataItem)
	***********************************************************************/

	::vl::WString SmbiosTypaDataItem::GetDesc()
	{
		return this->__vwsn_prop_Desc;
	}

	void SmbiosTypaDataItem::SetDesc(const ::vl::WString& __vwsn_value_)
	{
		(this->__vwsn_prop_Desc = __vwsn_value_);
	}

	::vl::vint SmbiosTypaDataItem::GetType()
	{
		return this->__vwsn_prop_Type;
	}

	void SmbiosTypaDataItem::SetType(::vl::vint __vwsn_value_)
	{
		(this->__vwsn_prop_Type = __vwsn_value_);
	}

	::vl::vint64_t SmbiosTypaDataItem::GetAddress()
	{
		return this->__vwsn_prop_Address;
	}

	void SmbiosTypaDataItem::SetAddress(::vl::vint64_t __vwsn_value_)
	{
		(this->__vwsn_prop_Address = __vwsn_value_);
	}

	SmbiosTypaDataItem::SmbiosTypaDataItem()
		: __vwsn_prop_Desc(::vl::WString(L"", false))
		, __vwsn_prop_Type(static_cast<::vl::vint>(0))
		, __vwsn_prop_Address(static_cast<::vl::vint64_t>(0L))
	{
	}

	SmbiosTypaDataItem::SmbiosTypaDataItem(const ::vl::vint& type, const ::vl::WString& desc, const ::vl::vint64_t& addr)
		: __vwsn_prop_Desc(::vl::WString(L"", false))
		, __vwsn_prop_Type(static_cast<::vl::vint>(0))
		, __vwsn_prop_Address(static_cast<::vl::vint64_t>(0L))
	{
		this->SetDesc(desc);
		this->SetType(type);
		this->SetAddress(addr);
	}

	/***********************************************************************
	Class (::Smbios::TextEditorConstructor)
	***********************************************************************/

	void TextEditorConstructor::__vwsn_Smbios_TextEditor_Initialize(::Smbios::TextEditor* __vwsn_this_)
	{
		(this->self = __vwsn_this_);
		{
			(this->textLabel = new ::vl::presentation::controls::GuiLabel(::vl::presentation::theme::ThemeName::Label));
		}
		{
			::vl::__vwsn::This(this->self)->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(::vl::__vwsn::This(this->textLabel)->GetBoundsComposition()));
		}
		{
			auto __vwsn_created_subscription_ = ::vl::Ptr<::vl::reflection::description::IValueSubscription>(new ::vl_workflow_global::__vwsnc7_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize__vl_reflection_description_IValueSubscription(this));
			::vl::__vwsn::EventAttach(::vl::__vwsn::This(__vwsn_created_subscription_.Obj())->ValueChanged, LAMBDA(::vl_workflow_global::__vwsnf23_Smbios_Smbios_TextEditorConstructor___vwsn_Smbios_TextEditor_Initialize_(this)));
			::vl::__vwsn::This(__vwsn_this_)->AddSubscription(__vwsn_created_subscription_);
		}
		{
			::vl::__vwsn::This(this->self)->SetFocusControl(static_cast<::vl::presentation::controls::GuiControl*>(this->textLabel));
		}
	}

	TextEditorConstructor::TextEditorConstructor()
		: self(static_cast<::Smbios::TextEditor*>(nullptr))
		, textLabel(static_cast<::vl::presentation::controls::GuiLabel*>(nullptr))
	{
	}

	/***********************************************************************
	Class (::Smbios::TextEditor)
	***********************************************************************/

	TextEditor::TextEditor()
	{
		auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString(L"Smbios::TextEditor", false));
		auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
		::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
		::vl::__vwsn::This(this)->__vwsn_Smbios_TextEditor_Initialize(this);
	}

	TextEditor::~TextEditor()
	{
		this->FinalizeInstanceRecursively(static_cast<::vl::presentation::templates::GuiTemplate*>(this));
	}
}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif