/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe MainWindow.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_HARDWARE
#define VCZH_WORKFLOW_COMPILER_GENERATED_HARDWARE

#include "HardwarePartialClasses.h"

#endif
