/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe MainWindow.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_HARDWAREREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_HARDWAREREFLECTION

#include "Hardware.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::Hardware::MainWindow)
			DECL_TYPE_INFO(::Hardware::MainWindowConstructor)
			DECL_TYPE_INFO(::Hardware::UI::CPUCoreTreeInternalProperty)
			DECL_TYPE_INFO(::Hardware::UI::HardwareTreeInternalProperty)
			DECL_TYPE_INFO(::Hardware::UI::IntWrapper)
			DECL_TYPE_INFO(::Hardware::UI::StringWrapper)
			DECL_TYPE_INFO(::Hardware::UI::TreeViewItemData)
#endif

			extern bool LoadHardwareTypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif

#endif
